### ISSUE TITLE
Clarity

### ISSUE THREAD

**Issue by Martin-Pitt** [steel-scene/steel-scene#4]
It might be good if you could expand out what this project is for and the mission.

It sounds really vague.

<details><summary>I came to this project and lots of questions popped in my head</summary>
- This seems like a generalised state machine?
- Could I use it to build states and transitions to drive something in WebVR maybe?
- Is this even for the web in the first place?
- Animations? 
- What kind of animations we talking here? 
- Is animations the goal, or something else?
- Is it animating user interfaces?
- Is it animating any css?
- Can I use it with css?
- Can I animate javascript objects/values?
- What about CSS Variables?
- Animation devtools?
- Where is the GUI of the devtools? Or the CLI command? (confused user by choice of wording)
</details>

**Comment by notoriousb1t** [comment]
The end goal of this project is to create animation devtools that can work locally and produce production ready code.  A side effect of that is creating a runtime abstraction that can conform to most animation engines.  At this point, We are working on creating just enough of the runtime library to start working on the tooling itself.  The paradigm is state based animations (adding in sequences later).  

Three options for devtools:

- use electron/NW.js + iframe injection to create essentially a specialize browser with the additional tooling, this has the nice effect of building it with whatever tools we want without worrying about polluting the website/web app
- build extensions for chrome/firefox.  I don't have as much experience here, so I don't know if there are any blocking factors
- build devtools you can insert as a script during development (mojs does this to some degree)

At this point, there is only one plugin being worked.  I started with GSAP because I think it is the most popular

**Comment by notoriousb1t** [comment]
One of the high level requirements of the project is that the output should be human readable and editable.

**Comment by notoriousb1t** [comment]
I just realized you had a whole bunch of questions collapsed 

>This seems like a generalized state machine? 
>Could I use it to build states and transitions to drive something in WebVR maybe?

Yes.  It would be possible to build a plugin for Canvas or WebVR because the core competency is a state management with transitions/keyframes between.

>Is this even for the web in the first place? 

The focus is web technologies.  I am not sure how we could apply it otherwise.

>What kind of animations we talking here? 
>Is animations the goal, or something else? 
>Is it animating user interfaces? 

My personal goal is to have a tool I can use for building interactive forms and intros.  A tool that I can use on an existing project with minimal changes.

>Can I animate javascript objects/values? 

We haven't really vetted that out.  In this initial state all the targets are elements, but maybe the JS api could be adapted to this.

>Is it animating any css? 

It should be possible to write a plugin that uses CSS Transitions/Animations and a little bit of JavaScript as the animation engine.

>Can I use it with css? 
>What about CSS Variables? 

I can't wrap my brain around how you would use it with CSS Variables, but I don't know, maybe?

>Animation devtools? 
>Where is the GUI of the devtools? Or the CLI command? (confused user by choice of wording)

Not yet even scaffolded.  We are trying to work out a simple runtime first because the devtools will be interacting with it directly.

**Comment by shshaw** [comment]
Re: Can I animate Javascript objects/values: I think that's going to be an essential feature to support THREE.js, Pixi, and most canvas libraries, though I'm not positive how that might look in the syntax.

**Comment by notoriousb1t** [comment]
I think we could support JavaScript objects as long as either A. the engine plugin can reference a unique identifier (like we are using for ids), or if we add a syntax to the html for creating new objects. Going to put a suggestion on the syntax thread.
